mod add_chat_member_command_tests;
mod common;
mod create_chat_command_tests;
mod create_cloud_attachment_command_tests;
mod delete_chat_member_command_tests;
mod delete_cloud_attachment_command_tests;
mod register_command_tests;
