version: '3.8'

services:
  scylla:
    image: scylladb/scylla:6.2.3
    container_name: scylla
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
    command: --smp 1

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  scylla_data:
